{
 "title": "Caddy",
 "description": "The dashboards gives an overview of the http requests made to a Caddy web server",
 "tags": [
  "k8s",
  "caddy"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(caddy_http_requests_total,namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(caddy_http_requests_total,pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP requests in the last 24h",
   "type": "stat",
   "description": "The number of requests in the last 24h",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(caddy_http_requests_total{handler=\"file_server\",namespace=\"$namespace\",pod=\"$pod\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "description": "Number of http requests",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "increase(caddy_http_requests_total{handler=\"file_server\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non 200 HTTP requests ",
   "type": "stat",
   "description": "HTTP requests that does not return a 200",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_request_duration_seconds_count{handler=\"file_server\",code!=\"200\",namespace=\"$namespace\",pod=\"$pod\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request by response code",
   "type": "timeseries",
   "description": "Request split by response code",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_request_duration_seconds_count{handler=\"file_server\",namespace=~\"$namespace\",pod=\"$pod\"}[$__rate_interval])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "description": "The request durations in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(caddy_http_request_duration_seconds_bucket{handler=\"file_server\",namespace=\"$namespace\",pod=\"$pod\"}) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum(caddy_http_request_duration_seconds_bucket{handler=\"file_server\",namespace=\"$namespace\",pod=\"$pod\"}) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.85, sum(caddy_http_request_duration_seconds_bucket{handler=\"file_server\",namespace=\"$namespace\",pod=\"$pod\"}) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean Response Size",
   "type": "timeseries",
   "description": "The mean size of the response in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, caddy_http_response_size_bytes_bucket{method=\"GET\",handler=\"file_server\",code=\"200\",namespace=\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}